### ISSUE TITLE
Time to release a patched version with new PR

### ISSUE THREAD

**Issue by m31271n** [withspectrum/react-app-rewire-styled-components#10]
Wait long time for new version with this [PR](https://github.com/withspectrum/react-app-rewire-styled-components/commit/1ff290767bee1b27945bf72ef35b2ba6bc5e1625).

Give us a new version, Your Majesty. 🤓

**Comment by mxstbr** [comment]
Oopsie, totally forgot! On it!

**Comment by mxstbr** [comment]
Published in v3.0.1!
