### ISSUE TITLE
wrong main field at package.json

### ISSUE THREAD

**Issue by m31271n** [withspectrum/react-app-rewire-styled-components#11]
https://github.com/withspectrum/react-app-rewire-styled-components/blob/1606d69d690a6dd9945ab352e0692d894c8401d6/package.json#L9

I think:

```
"main": "dist/index.js"
```

should be modified as: 

```
"main": "src/index.js"
```

It is a typo, right?

**Comment by kitop** [comment]
Having the same issue here, getting `Error: Cannot find module 'react-app-rewire-styled-components'`

**Comment by mxstbr** [comment]
No that should be `dist`, I just messed up publishing 🙄 One sec.

**Comment by mxstbr** [comment]
Fixed!

**Comment by mxstbr** [comment]
Fixed in v3.0.2!

**Comment by kitop** [comment]
Thank you! That was fast!!
