### ISSUE TITLE
Support for styled-components V4

### ISSUE THREAD

**Issue by cvetanov** [withspectrum/react-app-rewire-styled-components#23]
Hi,

I was wondering if we could add support for `styled-components` V4?
I could go ahead and do that with support from someone.

What would we need to change in order to support `styled-components` V4 (except the obvious update in `package.json`)?

Thanks,
Goce

**Comment by mxstbr** [comment]
Nothing else I think! PR very welcome :+1:

Just to note, s-c v4 has a Babel macro so this package is a little unnecessary. You can just do this in create-react-app instead:

```JS
import styled from 'styled-components/macro'
```

and you're using the babel plugin! See https://www.styled-components.com/docs/tooling#babel-macro

**Comment by cvetanov** [comment]
Thanks for the quick reply and the info.
It could be useful for those still on `react-scripts` < v2, so I will go ahead and create a PR with update to the peer dependencies.
