### ISSUE TITLE
Latest change is not published

### ISSUE THREAD

**Issue by ghengeveld** [withspectrum/react-app-rewire-styled-components#25]
3 months ago, styled-components v4 was [added to peerDependencies](https://github.com/withspectrum/react-app-rewire-styled-components/commit/86919d97a9895ca3ed080b80ad9a59b59e385c1a). However this change was never published to npm, causing a warning when installing the package while using styled-components v4.

Please publish this change to npm.

**Comment by mxstbr** [comment]
Congratulations, you are now an owner of this package on npm! 😉 

Feel free to publish a new version from master

**Comment by ghengeveld** [comment]
Well that was unexpected. But sure, I'll give it a go.

Meanwhile I've migrated away from `react-app-rewire-styled-components` (using `customize-cra` now) because it also requires `react-app-rewired@1.5.2`, which only works for CRA v1. In essence, `react-app-rewire-styled-components` cannot be used with CRA v2, so I consider it deprecated. Do you agree?

**Comment by ghengeveld** [comment]
For the record, here's my `config-overrides.js`:

```js
const { override, addBabelPlugin } = require("customize-cra")

module.exports = override(addBabelPlugin("styled-components"))
```

This requires `react-app-rewired@2` with `customize-cra` and `babel-plugin-styled-components`.

**Comment by mxstbr** [comment]
Yes, I agree.
