### ISSUE TITLE
displayName doesn't work

### ISSUE THREAD

**Issue by hundsim** [withspectrum/react-app-rewire-styled-components#9]
**What I've done**
1. Installed create-react-app
2. Added `react-app-rewired`, `react-app-rewire-styled-components` and `styled-components`
3. Tried both to use `react-app-rewire-styled-components` as is AND added config `"displayName": true`

**Expected behaviour**
In the browser dev tool, would like to have " nicer generated class names that include the components' name".

**Result**
The class names aren't changed, they have their default randomized look.
[Demo](https://codesandbox.io/s/6v0jq4pk9n)

**Comment by mxstbr** [comment]
Can you post your config please? It works perfectly fine for us so it's most likely a usage issue.

**Comment by hundsim** [comment]
Hm, weird.

The config was in the demo:


And here are two screenshots of the 
1. source code (styled component `Message`)
2. the resulting webpage
3. dev tools

**Firefox 59**
![screenshot 2018-03-18 22 49 12](https://user-images.githubusercontent.com/1907343/37571735-cd1823f0-2b00-11e8-8b4f-c523c3c80a4e.png)


**Chrome 65**
![screenshot 2018-03-18 22 51 36](https://user-images.githubusercontent.com/1907343/37571744-dfff624e-2b00-11e8-822f-6639d642e6cb.png)

**Comment by mxstbr** [comment]
Oh, you need to set up `react-app-rewired` properly by replacing `react-scripts start` in the package.json with `react-app-rewired start`, see https://github.com/timarney/react-app-rewired

**Comment by hundsim** [comment]
Oh 😳 

Thank you very much. And sorry for taking up your time!

**Comment by mxstbr** [comment]
No worries, happy to help! Next time, you'd probably get a faster answer if you ask [in the styled-components community](https://spectrum.chat/styled-components) though :wink:
